---
- debug:
    msg: "Check to see if EULA variables are accepted"
  failed_when: (end_user_license_aggreement_consent_server != "Y" )or (end_user_license_aggreement_consent_cli != "YES")



- name: Enable EPEL repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgkey: https://getfedora.org/static/352C64E5.txt
    gpgcheck: yes

- name: Add the MsSQL server repo
  yum_repository:
    name: mssql
    description: Microsoft SQL repo
    file: /etc/yum.repos.d/msprod
    baseurl: https://packages.microsoft.com/rhel/7/mssql-server/
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: Add MsSQL command line tools repo
  yum_repository:
    name: mssql-cli-tools
    description: MsSQL ommand line prod tools repo
    file: /etc/yum.repos.d/msprod
    baseurl: https://packages.microsoft.com/rhel/7/prod/
    gpgkey: https://packages.microsoft.com/keys/microsoft.asc
    gpgcheck: yes

- name: Remove older unixODBC files if performing upgrade
  yum:
    name: "{{ item }}"
    state: absent
  with_items: "{{unixODBC_packages}}"

- name: Update all packages
  yum:
    name: '*'
    state: latest

- name: Install mssql-server packages
  yum:
    name: "{{item}}"
    state: present
  with_items: "{{mssql_packages}}"

- name: Install pymssql for future playbooks against DB server
  pip:
    name: pymssql
    state: present

- name: Install mssql-cli-tool via command with args
  shell: ACCEPT_EULA=Y yum install mssql-tools -y
  when: install_cli

- name: Add mssql tools to .bashrc
  lineinfile:
    dest: "{{ ansible_user_dir}}/.bashrc"
    state: present
    line: 'export PATH="$PATH:/opt/mssql-tools/bin"'
  when: install_cli

- name: Add firewalld settings
  firewalld:
    zone: public
    port: 1433/tcp
    permanent: true
    state: enabled
  when: enable_iptables
  notify: restart iptables

- name: Stop any existing mssql-server
  service:
      name: mssql-server
      state: stopped

- name: Run mssql setup script
  shell:  MSSQL_PID="{{edition}}" MSSQL_SA_PASSWORD="{{db_password}}" /opt/mssql/bin/mssql-conf -n setup accept-eula
  register: setup_output
  failed_when: "'Setup has completed successfully. SQL Server is now starting.' not in setup_output.stdout"
